project:
  type: website
  output-dir: docs

website:
  title: "Data Science Capstone"
  navbar:
    left:
      - href: district_adm_plots.qmd
        text: Home
      - href: code_explanation.qmd
        text: Scraping Code
      - href: code_explanation2.qmd
        text: Scraping Example
    right:
      - icon: github
        href: https://github.com/havishak/sped-oregon-finance
        aria-label: GitHub
  search: false
format:
  html:
    theme: journal
    toc: true
# 
# editor: visual

