project:
  type: website
  output-dir: docs

website:
  title: "Data Science Capstone"
  navbar:
    left:
      - href: background.qmd
        text: Motivation  
      - href: code_explanation.qmd
        text: Scraping Code
      - href: code_explanation2.qmd
        text: Scraping Example
      - href: district_adm_plots.qmd
        text: Analysis
    right:
      - icon: github
        href: https://github.com/havishak/sped-oregon-finance
        aria-label: GitHub
  search: false
format:
  html:
    theme: journal
    toc: true
    mainfont: "serif"
    backgroundcolor: "#fffbf1"
    highlight: tango
# 
# editor: visual

